# Generated by Django 4.2.3 on 2023-07-14 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporter',
            name='verification_id',
            field=models.ImageField(blank=True, null=True, upload_to='reporter_ids/'),
        ),
    ]
