# Generated by Django 4.2.3 on 2023-07-24 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporter_management', '0004_rename_user_reporter_reporter_profile_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporter',
            name='verification_id_url',
        ),
    ]
