# Generated by Django 4.2.3 on 2023-07-14 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsor_name', models.CharField(max_length=255)),
                ('animal_fit_for_surgery', models.CharField(choices=[('vaccination', 'Vaccination'), ('sterilization', 'Sterilization'), ('OPD', 'OPD'), ('IPD', 'IPD'), ('adoption', 'Adoption'), ('post_op_care', 'Post Op Care'), ('other', 'Other')], max_length=255, null=True)),
                ('sponsor_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('sponsor_logo', models.ImageField(null=True, upload_to='sponsor_logos/')),
                ('sponsor_logo_url', models.URLField(blank=True, default='')),
            ],
        ),
    ]
