# Generated by Django 4.2.3 on 2023-07-23 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor_management', '0003_sponsor_sponsor_profile_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsor',
            name='sponsor_logo_url',
        ),
    ]
