# Generated by Django 4.2.3 on 2023-07-23 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor_management', '0004_remove_sponsor_sponsor_logo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='animal_fit_for_surgery',
            field=models.CharField(choices=[('Vaccination', 'Vaccination'), ('Sterilization', 'Sterilization'), ('OPD', 'OPD'), ('IPD', 'IPD'), ('Adoption', 'Adoption'), ('Post Op Care', 'Post Op Care'), ('Other', 'Other')], max_length=255, null=True),
        ),
    ]
