# Generated by Django 4.2.3 on 2024-02-25 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ngo_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animalSpecies', models.CharField(blank=True, choices=[('Dog', 'Dog'), ('Cat', 'Cat'), ('Bird', 'Bird'), ('Other', 'Other')], max_length=255, null=True)),
                ('animalBreed', models.CharField(blank=True, choices=[('Indie', 'Indie'), ('Pet', 'Pet'), ('Other', 'Other')], max_length=255, null=True)),
                ('animalAge', models.CharField(blank=True, choices=[('0-1', '0-1'), ('1-5', '1-5'), ('5-10', '5-10'), ('10+', '10+')], max_length=255, null=True)),
                ('animalTemperament', models.CharField(blank=True, choices=[('Friendly', 'Friendly'), ('Aggressive', 'Aggressive'), ('Scared', 'Scared'), ('Other', 'Other')], max_length=255, null=True)),
                ('animalGender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=255, null=True)),
                ('animalPregnant', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Not Sure', 'Not Sure')], max_length=255, null=True)),
                ('animalMarking', models.CharField(blank=True, max_length=255, null=True)),
                ('animalColor', models.CharField(blank=True, max_length=255, null=True)),
                ('animalCatchable', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=255, null=True)),
                ('animalWeight', models.CharField(blank=True, max_length=255, null=True)),
                ('admissionReason', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('type_of_case', models.CharField(choices=[('Vaccination', 'Vaccination'), ('Sterilization', 'Sterilization'), ('OPD', 'OPD'), ('IPD', 'IPD')], max_length=255, null=True)),
                ('status_of_case', models.CharField(choices=[('Reported', 'Reported'), ('Admitted', 'Admitted'), ('Blood Test', 'Blood Test'), ('Operation', 'Operation'), ('Post Operation', 'Post Operation'), ('Released', 'Released')], max_length=255, null=True)),
                ('mortality_of_case', models.CharField(choices=[('Healthy', 'Healthy'), ('Unhealthy', 'Unhealthy'), ('Fatal', 'Fatal')], max_length=255, null=True)),
                ('cause_of_failure', models.TextField(blank=True, null=True)),
                ('case_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_when_created', models.DateTimeField(auto_now_add=True)),
                ('date_when_last_updated', models.DateTimeField(auto_now=True)),
                ('ngo_linked_with_this_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='ngo_management.ngo')),
                ('user_adding_this_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OperationDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vetName', models.CharField(blank=True, max_length=255, null=True)),
                ('operationDate', models.DateField(blank=True, null=True)),
                ('operationStartTime', models.TimeField(blank=True, null=True)),
                ('operationEndTime', models.TimeField(blank=True, null=True)),
                ('operationOutcome', models.CharField(blank=True, choices=[('Success', 'Success'), ('Failure', 'Failure'), ('Complicated', 'Complicated')], max_length=20, null=True)),
                ('case_linked', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='case_management.case')),
            ],
        ),
        migrations.CreateModel(
            name='PostOperationDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('popComment', models.TextField(blank=True, null=True)),
                ('popFacility', models.CharField(blank=True, choices=[('In Shelter', 'In Shelter'), ('Not in shelter', 'Not in shelter'), ('On Street', 'On Street'), ('Other', 'Other')], max_length=20, null=True)),
                ('popExpectedDays', models.CharField(blank=True, max_length=255, null=True)),
                ('popStartDate', models.DateField(blank=True, null=True)),
                ('popEndDate', models.DateField(blank=True, null=True)),
                ('releaseDate', models.DateField(blank=True, null=True)),
                ('euthanized', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('case_linked', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='case_management.case')),
            ],
        ),
        migrations.CreateModel(
            name='TreatmentRecordImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatmentRecordImage', models.ImageField(blank=True, null=True, upload_to='operational_detail/treatment_record/')),
                ('treatment_record_image_upload_date', models.DateField(auto_now_add=True)),
                ('operation_linked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatmentRecordImage', to='case_management.operationdetail')),
            ],
        ),
        migrations.CreateModel(
            name='ReportingDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporterName', models.CharField(blank=True, max_length=255, null=True)),
                ('reporterContact', models.CharField(blank=True, max_length=255, null=True)),
                ('reporterAltContact', models.CharField(blank=True, max_length=255, null=True)),
                ('reporterEmail', models.CharField(blank=True, max_length=255, null=True)),
                ('landmark', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('pincode', models.CharField(blank=True, max_length=255, null=True)),
                ('reportedDate', models.DateField(blank=True, null=True)),
                ('reportedTime', models.TimeField(blank=True, null=True)),
                ('pickupDate', models.DateField(blank=True, null=True)),
                ('pickupTime', models.TimeField(blank=True, null=True)),
                ('frontImage', models.ImageField(blank=True, null=True, upload_to='sponsor_logos/front/')),
                ('backImage', models.ImageField(blank=True, null=True, upload_to='sponsor_logos/back/')),
                ('consentFormImage', models.ImageField(blank=True, null=True, upload_to='sponsor_logos/consent_form/')),
                ('case_linked', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='case_management.case')),
            ],
        ),
        migrations.CreateModel(
            name='ReleasePictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('releasePictures', models.ImageField(blank=True, null=True, upload_to='post_operation_detail/release_picture/')),
                ('release_pictures_upload_date', models.DateField(auto_now_add=True)),
                ('post_operation_linked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releasePictures', to='case_management.postoperationdetail')),
            ],
        ),
        migrations.CreateModel(
            name='PopPictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('popPictures', models.ImageField(blank=True, null=True, upload_to='post_operation_detail/picture/')),
                ('pop_pictures_upload_date', models.DateField(auto_now_add=True)),
                ('post_operation_linked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='popPictures', to='case_management.postoperationdetail')),
            ],
        ),
        migrations.CreateModel(
            name='OrganImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organImage', models.ImageField(blank=True, null=True, upload_to='operational_detail/organ_image/')),
                ('organ_image_upload_date', models.DateField(auto_now_add=True)),
                ('operation_linked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organImage', to='case_management.operationdetail')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalPrescriptionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicalPrescriptionImage', models.ImageField(blank=True, null=True, upload_to='operational_detail/prescription/')),
                ('medical_prescription_image_upload_date', models.DateField()),
                ('operation_linked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicalPrescriptionImage', to='case_management.operationdetail')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicalHistory', models.CharField(blank=True, max_length=255, null=True)),
                ('vaccinationStatus', models.CharField(blank=True, choices=[('Already Done', 'Already Done'), ('To be done in NGO', 'To be done in NGO'), ('Not Done', 'Not Done'), ('Unsure', 'Unsure')], max_length=20, null=True)),
                ('dewormed', models.CharField(blank=True, choices=[('Already Done', 'Already Done'), ('To be done in NGO', 'To be done in NGO'), ('Not Done', 'Not Done'), ('Unsure', 'Unsure')], max_length=20, null=True)),
                ('fitForSurgery', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Unsure', 'Unsure')], max_length=10, null=True)),
                ('otherDetails', models.CharField(blank=True, max_length=255, null=True)),
                ('admissionDate', models.DateField(blank=True, null=True)),
                ('case_linked', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='case_management.case')),
            ],
        ),
        migrations.CreateModel(
            name='FeedingRecordImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedingRecordImage', models.ImageField(blank=True, null=True, upload_to='medical_detail/feeding_record/')),
                ('feeding_record_image_upload_date', models.DateField(auto_now_add=True)),
                ('medical_linked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedingRecordImage', to='case_management.medicaldetail')),
            ],
        ),
        migrations.CreateModel(
            name='BloodReportImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloodReportImage', models.ImageField(blank=True, null=True, upload_to='medical_detail/blood_repoort/')),
                ('blood_report_date', models.DateField()),
                ('medical_linked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloodReportImage', to='case_management.medicaldetail')),
            ],
        ),
        migrations.CreateModel(
            name='AnimalPictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animalPictures', models.ImageField(blank=True, null=True, upload_to='animal_images/')),
                ('animal_picture_upload_date', models.DateField(auto_now_add=True)),
                ('animal_linked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animalPictures', to='case_management.animaldetail')),
            ],
        ),
        migrations.AddField(
            model_name='animaldetail',
            name='case_linked',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='case_management.case'),
        ),
    ]
