# Generated by Django 4.2.3 on 2023-07-15 08:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('type_of_case', models.CharField(choices=[('vaccination', 'Vaccination'), ('sterilization', 'Sterilization'), ('OPD', 'OPD'), ('IPD', 'IPD')], max_length=255, null=True)),
                ('status_of_case', models.CharField(choices=[('reported', 'Reported'), ('admitted', 'Admitted'), ('blood_test', 'Blood Test'), ('operation', 'Bperation'), ('post_operation', 'Post Operation'), ('released', 'Released')], max_length=255, null=True)),
                ('mortality_of_case', models.CharField(choices=[('healthy', 'Healthy'), ('unhealthy', 'Unhealthy'), ('fatal', 'Fatal')], max_length=255, null=True)),
                ('cause_of_failure', models.TextField(null=True)),
                ('case_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_adding_this_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReportingDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporterName', models.CharField(max_length=255)),
                ('reporterContact', models.CharField(max_length=255)),
                ('reporterAltContact', models.CharField(blank=True, max_length=255, null=True)),
                ('reporterEmail', models.CharField(blank=True, max_length=255, null=True)),
                ('landmark', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('pincode', models.CharField(max_length=255)),
                ('reportedDate', models.DateField(blank=True, null=True)),
                ('reportedTime', models.TimeField(blank=True, null=True)),
                ('pickupDate', models.DateField(blank=True, null=True)),
                ('pickupTime', models.TimeField(blank=True, null=True)),
                ('frontImage', models.ImageField(blank=True, null=True, upload_to='sponsor_logos/front/')),
                ('frontImageURL', models.URLField(blank=True, default='')),
                ('backImage', models.ImageField(blank=True, null=True, upload_to='sponsor_logos/back/')),
                ('backImageURL', models.URLField(blank=True, default='')),
                ('consentFormImage', models.ImageField(blank=True, null=True, upload_to='sponsor_logos/consent_form/')),
                ('consentFormImageURL', models.URLField(blank=True, default='')),
                ('case_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='case_management.case')),
            ],
        ),
        migrations.CreateModel(
            name='PostOperationDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('popComment', models.TextField(null=True)),
                ('popFacility', models.CharField(choices=[('In Shelter', 'In Shelter'), ('Not in shelter', 'Not in shelter'), ('On Street', 'On Street'), ('Other', 'Other')], max_length=20, null=True)),
                ('popExpectedDays', models.CharField(max_length=255, null=True)),
                ('popStartDate', models.DateField(null=True)),
                ('popEndDate', models.DateField(null=True)),
                ('releaseDate', models.DateField(null=True)),
                ('euthanized', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True)),
                ('comments', models.TextField(null=True)),
                ('popPictures', models.ImageField(blank=True, null=True, upload_to='post_operation_detail/picture/')),
                ('popPicturesURL', models.URLField(blank=True, default='')),
                ('releasePictures', models.ImageField(blank=True, null=True, upload_to='post_operation_detail/release_picture/')),
                ('releasePicturesURL', models.URLField(blank=True, default='')),
                ('case_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='case_management.case')),
            ],
        ),
        migrations.CreateModel(
            name='OperationDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vetName', models.CharField(max_length=255, null=True)),
                ('operationDate', models.DateField(null=True)),
                ('operationStartTime', models.TimeField(null=True)),
                ('operationEndTime', models.TimeField(null=True)),
                ('operationOutcome', models.CharField(choices=[('Success', 'Success'), ('Failure', 'Failure'), ('Complicated', 'Complicated')], max_length=20, null=True)),
                ('medicalPrescriptionImage', models.ImageField(blank=True, null=True, upload_to='operational_detail/prescription/')),
                ('medicalPrescriptionImageURL', models.URLField(blank=True, default='')),
                ('treatmentRecordImage', models.ImageField(blank=True, null=True, upload_to='operational_detail/treatment_record/')),
                ('treatmentRecordImageURL', models.URLField(blank=True, default='')),
                ('organImage', models.ImageField(blank=True, null=True, upload_to='operational_detail/organ_image/')),
                ('organImageURL', models.URLField(blank=True, default='')),
                ('case_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='case_management.case')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicalHistory', models.CharField(blank=True, max_length=255, null=True)),
                ('vaccinationStatus', models.CharField(blank=True, choices=[('Already Done', 'Already Done'), ('To be done in NGO', 'To be done in NGO'), ('Not Done', 'Not Done'), ('Unsure', 'Unsure')], max_length=20, null=True)),
                ('dewormed', models.CharField(blank=True, choices=[('Already Done', 'Already Done'), ('To be done in NGO', 'To be done in NGO'), ('Not Done', 'Not Done'), ('Unsure', 'Unsure')], max_length=20, null=True)),
                ('fitForSurgery', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Unsure', 'Unsure')], max_length=10, null=True)),
                ('otherDetails', models.CharField(blank=True, max_length=255, null=True)),
                ('admissionDate', models.DateField(blank=True, null=True)),
                ('feedingRecordImage', models.ImageField(blank=True, null=True, upload_to='medical_detail/feeding_record/')),
                ('feedingRecordImageURL', models.URLField(blank=True, default='')),
                ('bloodReportImage', models.ImageField(blank=True, null=True, upload_to='medical_detail/blood_repoort/')),
                ('bloodReportImageURL', models.URLField(blank=True, default='')),
                ('case_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='case_management.case')),
            ],
        ),
        migrations.CreateModel(
            name='AnimalDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animalSpecies', models.CharField(blank=True, choices=[('Indie', 'Indie'), ('Pet', 'Pet'), ('Other', 'Other')], max_length=255, null=True)),
                ('animalBreed', models.CharField(blank=True, choices=[('Indie', 'Indie'), ('Pet', 'Pet'), ('Other', 'Other')], max_length=255, null=True)),
                ('animalAge', models.CharField(blank=True, choices=[('0-1', '0-1'), ('1-5', '1-5'), ('5-10', '5-10'), ('10+', '10+')], max_length=255, null=True)),
                ('animalTemperament', models.CharField(blank=True, choices=[('Friendly', 'Friendly'), ('Aggressive', 'Aggressive'), ('Scared', 'Scared'), ('Other', 'Other')], max_length=255, null=True)),
                ('animalGender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=255, null=True)),
                ('animalPregnant', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Not Sure', 'Not Sure')], max_length=255, null=True)),
                ('animalMarking', models.CharField(blank=True, max_length=255, null=True)),
                ('animalColor', models.CharField(blank=True, max_length=255, null=True)),
                ('animalCatchable', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Not Sure', 'Not Sure')], max_length=255, null=True)),
                ('animalWeight', models.CharField(blank=True, max_length=255, null=True)),
                ('admissionReason', models.CharField(blank=True, max_length=255, null=True)),
                ('animalPictures', models.ImageField(blank=True, null=True, upload_to='animal_images/')),
                ('animalPicturesURL', models.URLField(blank=True, default='')),
                ('case_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='case_management.case')),
            ],
        ),
    ]
