# Generated by Django 4.2.3 on 2023-07-15 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='cause_of_failure',
            field=models.TextField(blank=True, null=True),
        ),
    ]
