# Generated by Django 4.2.3 on 2023-07-15 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0002_alter_case_cause_of_failure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='status_of_case',
            field=models.CharField(choices=[('reported', 'Reported'), ('admitted', 'Admitted'), ('blood_test', 'Blood Test'), ('operation', 'Operation'), ('post_operation', 'Post Operation'), ('released', 'Released')], max_length=255, null=True),
        ),
    ]
