# Generated by Django 4.2.3 on 2023-07-15 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0003_alter_case_status_of_case'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animaldetail',
            name='animalCatchable',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='animaldetail',
            name='animalSpecies',
            field=models.CharField(blank=True, choices=[('Dog', 'Dog'), ('Cat', 'Cat'), ('Bird', 'Bird'), ('Other', 'Other')], max_length=255, null=True),
        ),
    ]
