# Generated by Django 4.2.3 on 2023-07-15 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0004_alter_animaldetail_animalcatchable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postoperationdetail',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
