# Generated by Django 4.2.3 on 2023-07-17 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0006_alter_case_mortality_of_case_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportingdetail',
            old_name='case_id',
            new_name='id_of_case',
        ),
    ]
