# Generated by Django 4.2.3 on 2023-07-17 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0007_rename_case_id_reportingdetail_id_of_case'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportingdetail',
            old_name='id_of_case',
            new_name='case_linked',
        ),
    ]
