# Generated by Django 4.2.3 on 2023-07-17 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0009_remove_reportingdetail_backimageurl_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animaldetail',
            name='animalPicturesURL',
        ),
    ]
