# Generated by Django 4.2.3 on 2023-07-18 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0011_rename_case_id_animaldetail_case_linked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationdetail',
            name='operationDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='operationdetail',
            name='operationEndTime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='operationdetail',
            name='operationOutcome',
            field=models.CharField(blank=True, choices=[('Success', 'Success'), ('Failure', 'Failure'), ('Complicated', 'Complicated')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='operationdetail',
            name='operationStartTime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='operationdetail',
            name='vetName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
