# Generated by Django 4.2.3 on 2023-07-18 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0012_alter_operationdetail_operationdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postoperationdetail',
            name='euthanized',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='postoperationdetail',
            name='popComment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postoperationdetail',
            name='popEndDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postoperationdetail',
            name='popExpectedDays',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='postoperationdetail',
            name='popFacility',
            field=models.CharField(blank=True, choices=[('In Shelter', 'In Shelter'), ('Not in shelter', 'Not in shelter'), ('On Street', 'On Street'), ('Other', 'Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='postoperationdetail',
            name='popStartDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postoperationdetail',
            name='releaseDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
