# Generated by Django 4.2.3 on 2023-07-19 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('case_management', '0013_alter_postoperationdetail_euthanized_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='user_adding_this_case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
