# Generated by Django 4.2.3 on 2023-07-20 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0016_alter_reportingdetail_case_linked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animaldetail',
            name='case_linked',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='case_management.case'),
        ),
        migrations.AlterField(
            model_name='medicaldetail',
            name='case_linked',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='case_management.case'),
        ),
        migrations.AlterField(
            model_name='operationdetail',
            name='case_linked',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='case_management.case'),
        ),
        migrations.AlterField(
            model_name='postoperationdetail',
            name='case_linked',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='case_management.case'),
        ),
    ]
