# Generated by Django 4.2.3 on 2023-07-24 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0017_alter_animaldetail_case_linked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportingdetail',
            name='landmark',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='reportingdetail',
            name='location',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='reportingdetail',
            name='pincode',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='reportingdetail',
            name='reporterContact',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='reportingdetail',
            name='reporterName',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
