# Generated by Django 4.2.3 on 2023-07-26 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0019_alter_reportingdetail_landmark_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportingdetail',
            name='landmark',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='reportingdetail',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='reportingdetail',
            name='pincode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='reportingdetail',
            name='reporterContact',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='reportingdetail',
            name='reporterName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
