# Generated by Django 4.2.3 on 2023-07-27 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0021_alter_postoperationdetail_euthanized'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postoperationdetail',
            name='euthanized',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, null=True),
        ),
    ]
