# Generated by Django 4.2.3 on 2023-07-29 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0023_animaldetail_animalpictures02_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animaldetail',
            name='animalPictures',
        ),
        migrations.RemoveField(
            model_name='animaldetail',
            name='animalPictures02',
        ),
        migrations.RemoveField(
            model_name='animaldetail',
            name='animalPictures03',
        ),
        migrations.RemoveField(
            model_name='animaldetail',
            name='animalPictures04',
        ),
        migrations.RemoveField(
            model_name='animaldetail',
            name='animalPictures05',
        ),
        migrations.CreateModel(
            name='AnimalPictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animalPictures', models.FileField(blank=True, null=True, upload_to='animal_images/')),
                ('animal_detail_linked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='case_management.animaldetail')),
            ],
        ),
    ]
