# Generated by Django 4.2.3 on 2023-07-31 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0025_animaldetail_animalpictures_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animaldetail',
            name='animalPictures02',
        ),
        migrations.RemoveField(
            model_name='animaldetail',
            name='animalPictures03',
        ),
        migrations.RemoveField(
            model_name='animaldetail',
            name='animalPictures04',
        ),
        migrations.RemoveField(
            model_name='animaldetail',
            name='animalPictures05',
        ),
        migrations.AlterField(
            model_name='animaldetail',
            name='animalPictures',
            field=models.ImageField(blank=True, null=True, upload_to='animal_images/'),
        ),
    ]
