# Generated by Django 4.2.3 on 2023-08-01 16:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0026_remove_animaldetail_animalpictures02_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animaldetail',
            name='animalPictures',
        ),
        migrations.AddField(
            model_name='case',
            name='date_when_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='case',
            name='date_when_last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
