# Generated by Django 4.2.3 on 2023-08-05 07:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0028_animalpictures'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalpictures',
            name='animal_picture_upload_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
