# Generated by Django 4.2.3 on 2023-08-05 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0029_animalpictures_animal_picture_upload_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicaldetail',
            name='feedingRecordImage',
        ),
        migrations.CreateModel(
            name='FeedingRecordImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedingRecordImage', models.ImageField(blank=True, null=True, upload_to='medical_detail/feeding_record/')),
                ('feeding_record_image_upload_date', models.DateField(auto_now_add=True)),
                ('medical_linked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedingRecordImage', to='case_management.medicaldetail')),
            ],
        ),
    ]
