# Generated by Django 4.2.3 on 2023-08-07 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0031_remove_operationdetail_organimage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicaldetail',
            name='bloodReportImage',
        ),
        migrations.CreateModel(
            name='BloodReportImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloodReportImage', models.ImageField(blank=True, null=True, upload_to='medical_detail/blood_repoort/')),
                ('blood_report_date', models.DateField()),
                ('medical_linked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloodReportImage', to='case_management.medicaldetail')),
            ],
        ),
    ]
