# Generated by Django 4.2.3 on 2023-08-11 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0032_remove_medicaldetail_bloodreportimage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operationdetail',
            name='medicalPrescriptionImage',
        ),
        migrations.CreateModel(
            name='MedicalPrescriptionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicalPrescriptionImage', models.ImageField(blank=True, null=True, upload_to='operational_detail/prescription/')),
                ('medical_prescription_image_upload_date', models.DateField()),
                ('operation_linked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicalPrescriptionImage', to='case_management.operationdetail')),
            ],
        ),
    ]
