# Generated by Django 4.2.3 on 2024-02-25 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('user_contact', models.CharField(max_length=20)),
                ('email', models.CharField(default='', max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('type_of_user_in_ngo', models.CharField(blank=True, choices=[('Founder', 'Founder'), ('Manager', 'Manager'), ('Worker', 'Worker')], max_length=255, null=True)),
                ('profilePhoto', models.ImageField(blank=True, null=True, upload_to='profile_photo/')),
                ('groups', models.ManyToManyField(blank=True, related_name='profile_set', related_query_name='profile', to='auth.group', verbose_name='groups')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
