# Generated by Django 4.2.3 on 2024-02-25 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ngo_management', '0001_initial'),
        ('authorization', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ngo_linked_with_this_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ngo', to='ngo_management.ngo'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='profile_set', related_query_name='profile', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
