# Generated by Django 4.2.3 on 2023-07-18 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_remove_profile_user_profile_email_profile_groups_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user_name',
            new_name='username',
        ),
    ]
