# Generated by Django 4.2.3 on 2023-07-25 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0004_alter_profile_user_contact_alter_profile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profilePhoto',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photo/'),
        ),
    ]
