# Generated by Django 4.2.3 on 2023-07-27 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ngo_management', '0003_ngo_ngo_logo'),
        ('authorization', '0005_profile_profilephoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ngo_linked_with_this_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='ngo_management.ngo'),
        ),
    ]
