# Generated by Django 4.2.3 on 2023-07-27 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0006_profile_ngo_linked_with_this_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='type_of_user_in_ngo',
            field=models.CharField(blank=True, choices=[('Founder', 'Founder'), ('Manager', 'Manager'), ('Worker', 'Worker')], max_length=255, null=True),
        ),
    ]
