# Generated by Django 4.2.3 on 2023-07-27 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ngo_management', '0004_alter_ngo_id'),
        ('authorization', '0007_profile_type_of_user_in_ngo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ngo_linked_with_this_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ngo', to='ngo_management.ngo'),
        ),
    ]
