# Generated by Django 4.2.3 on 2023-07-28 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0008_alter_profile_ngo_linked_with_this_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_active',
            field=models.CharField(choices=[('Active', 'Active'), ('Not Active', 'Not Active')], default='Active', max_length=15),
        ),
    ]
