# Generated by Django 4.2.3 on 2023-08-07 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0008_alter_profile_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_active',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('Not Active', 'Not Active')], max_length=15, null=True),
        ),
    ]
