# Generated by Django 4.2.3 on 2023-07-28 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0009_alter_profile_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_active',
            field=models.CharField(choices=[('Not Active', 'Not Active'), ('Active', 'Active')], max_length=15),
        ),
    ]
