# Generated by Django 4.2.3 on 2023-07-14 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vet_name', models.CharField(max_length=255)),
                ('registration_id', models.CharField(max_length=255)),
                ('vet_certification', models.ImageField(null=True, upload_to='vet_certifications/')),
                ('vet_certification_url', models.URLField(blank=True, default='')),
                ('verification_id', models.ImageField(null=True, upload_to='verification_ids/')),
                ('verification_id_url', models.URLField(blank=True, default='')),
            ],
        ),
    ]
