# Generated by Django 4.2.3 on 2023-07-14 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vet_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vet',
            name='verification_id',
            field=models.ImageField(blank=True, null=True, upload_to='verification_ids/'),
        ),
        migrations.AlterField(
            model_name='vet',
            name='vet_certification',
            field=models.ImageField(blank=True, null=True, upload_to='vet_certifications/'),
        ),
    ]
