# Generated by Django 4.2.3 on 2023-07-14 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vet_management', '0002_alter_vet_verification_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vet',
            name='vet_profile_creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vets', to=settings.AUTH_USER_MODEL),
        ),
    ]
