# Generated by Django 4.2.3 on 2023-07-24 07:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ngo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngo_name', models.CharField(max_length=255)),
                ('darpan_id', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('mission_statement', models.CharField(max_length=255)),
                ('helpline_number', models.CharField(max_length=255)),
                ('alternate_helpline_number', models.CharField(max_length=255)),
                ('facebook_page', models.CharField(max_length=255)),
                ('linkedin_page', models.CharField(max_length=255)),
                ('instagram_page', models.CharField(max_length=255)),
                ('twitter_page', models.CharField(max_length=255)),
                ('ngo_email', models.CharField(max_length=255)),
                ('ngo_website', models.CharField(max_length=255)),
                ('ngo_profile_creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ngos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
