# Generated by Django 4.2.3 on 2023-07-24 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngo',
            name='alternate_helpline_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ngo',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ngo',
            name='facebook_page',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ngo',
            name='helpline_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ngo',
            name='instagram_page',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ngo',
            name='linkedin_page',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ngo',
            name='mission_statement',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ngo',
            name='ngo_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ngo',
            name='ngo_website',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ngo',
            name='twitter_page',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
