# Generated by Django 4.2.3 on 2023-07-24 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo_management', '0002_alter_ngo_alternate_helpline_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngo',
            name='ngo_logo',
            field=models.ImageField(blank=True, null=True, upload_to='ngo/'),
        ),
    ]
