# Generated by Django 4.2.3 on 2023-07-27 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo_management', '0003_ngo_ngo_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
