# Generated by Django 4.2.3 on 2023-10-21 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo_management', '0004_alter_ngo_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngo',
            name='ngo_address',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ngo',
            name='offline_cases',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
